version: '2.3'

services:

  notebooks:
    image: jupyter/tensorflow-notebook

    volumes:
      - ./:/code
      - ./data:/data

    working_dir: /code/notebooks

    ports:
      - 8888:8888

    command: jupyter lab --no-browser --allow-root --ip 0.0.0.0 --NotebookApp.custom_display_url=http://localhost:8888


  ipython-shell:
    # image: jupyter/tensorflow-notebook
    image: tensorflow/tensorflow:latest-gpu-py3
    runtime: nvidia

    volumes:
      - ./:/code
      - ./data:/data

    working_dir: /code/superpixel_segmentation

    ports:
      - 6006:6006

    stdin_open: true
    tty: true

    command: ipython --TerminalInteractiveShell.editing_mode=vi
